feat: support "se:cdp" capability
aerokube/selenoid pull request #1354
Opened 2023-06-19 10:52 UTC by DudaGod

Implement `se:cdp` capability to be able to connect from playwright. Related PR to pwt - https://github.com/microsoft/playwright/pull/23341.

Related issues:
- https://github.com/aerokube/selenoid/issues/1063

2023-06-19 13:27 UTC, DudaGod commented
Fixed

2023-06-19 13:40 UTC, vania-pooh commented on selenoid.go
> +		return ret, fmt.Errorf("stringify body response: %v", err)
return nil, fmt.Errorf()

2023-06-19 13:43 UTC, vania-pooh requested changes

2023-06-19 13:43 UTC, vania-pooh commented on selenoid.go
> +		return input, fmt.Errorf("parse body response: %v", err)
return nil, fmt.Errorf()

2023-06-19 13:43 UTC, vania-pooh commented on selenoid.go
> +		resp.Body = io.NopCloser(bytes.NewBufferString(string(newBody)))
change to bytes.NewReader(newBody)

2023-06-19 14:21 UTC, vania-pooh requested changes

2023-06-19 14:21 UTC, vania-pooh commented on selenoid.go
>  		tee := io.TeeReader(resp.Body, w)
Probably need to use `body` or `newBody` instead of `resp.Body` here to prevent using already read io.Reader.

2023-06-19 14:24 UTC, vania-pooh commented on selenoid.go
>  		tee := io.TeeReader(resp.Body, w)
Or you could simply get ID field from already parsed body.

2023-06-20 09:15 UTC, vania-pooh approved these changes

2023-06-20 09:18 UTC, merged

2023-07-04 15:47 UTC, martingrossmann commented
@vania-pooh Hi, is'nt this change worth a new release?

2023-07-05 06:40 UTC, vania-pooh commented
@martingrossmann will release during next days.